task:
  type: extraction
  use_reflection: true

model:
  model_name_or_path: Qwen/Qwen3.5-9B
  api_key: sk-iyyndybfqyuzdrvpojzvfehfpnbqdktdhdccubvgabifeyqk
  base_url: https://api.siliconflow.cn/v1

extraction:
  use_file: true
  file_path: "/Users/mac/Desktop/kg/kg/data/input_files/15-大模型 RAG 经验面.pdf"
  language: auto
  show_trajectory: true

generation:
  triplets_json_path: "/Users/mac/Desktop/kg/kg/data/input_files/reverse_generation_triplets.json"
  show_trajectory: true

agent:
  chunk_char_limit: 1024
  chunk_overlap_sentences: 2
