model:
  model_name_or_path: deepseek-chat # model name
  api_key: "your_api_key" # your API key for the model with API service.
  base_url: "https://api.deepseek.com" # base URL for the API service.

extraction:
  task: NER  # task type, chosen from Base, NER, RE, EE.
  text: Finally , every other year , ELRA organizes a major conference LREC , the International Language Resources and Evaluation Conference . # input text for the extraction task. No need if use_file is set to true.
  constraint: ["algorithm", "conference", "else", "product", "task", "field", "metrics", "organization", "researcher", "program language", "country", "location", "person", "university"] # Specified entity types for the named entity recognition task. Default set to empty.
  use_file: false # whether to use a file for the input text.
  mode: quick # extraction mode, chosen from quick, detailed, customized. Default set to quick. See src/config.yaml for more details.
  language: auto # extraction language, chosen from auto, zh, en. Default set to auto.
  update_case: false # whether to update the case repository. Default set to false.
  show_trajectory: false # whether to display the extracted intermediate steps
