model:
  embedding_model: all-MiniLM-L6-v2

agent:
  language: auto # language mode, chosen from auto, zh, en. Default is auto.
  chunk_token_limit: 1024
  mode:
    quick:
      schema_agent: get_deduced_schema
      extraction_agent: extract_information_direct
    standard:
      schema_agent: get_deduced_schema
      extraction_agent: extract_information_with_case
      reflection_agent: reflect_with_case
    customized:
      schema_agent:  get_retrieved_schema
      extraction_agent: extract_information_direct
